name: 🐞 Bug Report
description: Report something that is not working as expected
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug for NFC Cassette Cover Generator.
        Please fill out the details below.

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: e.g. v0.1.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Error messages
      description: Paste screenshots or error logs here if applicable.
    validations:
      required: false