name: ❓ Question / Support
description: Ask a question about usage or setup
title: "[Question]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Need help with NFC Cassette Cover Generator?
        Fill out the details below.

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: e.g. v0.1.0
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Describe what you need help with.
    validations:
      required: true